spring:
  application:
    name: letsgo-springboot
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://***REMOVED***:3306/mydb
    username: ***REMOVED***
    password: ***REMOVED***

mybatis:
  mapper-locations: classpath:mappers/myScheduleMapper.xml