spring:
  application:
    name: letsgo-springboot
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://43.203.228.33:3306/mydb
    username: mydbid
    password: mydbpw

mybatis:
  mapper-locations: classpath:mappers/myScheduleMapper.xml